#version: '3.8'
#
#services:
#  api-markbot:
#    build: api/. # здесь мы говорим, где берем рецепт для нашего web контейнера. Но некоторые крутые пишут параметры context:... и dockerfile:..., если место и имя файла отличается
#    env_file:
#      - .env
#    ports:
#      - "3000:3000"
#    volumes: # называется томами, нужны для синхронизации данных контейнера и хоста(нашего компьютера). Вообще используются овер где и как, они очень полезны, вот один яркий пример: внутри контейнера будут писаться логи, но без указания тома они там и останутся. Чтобы их увидеть, тебе придется зайти внутрь контейнера и посмотреть там - изменения не будут отображаться в IDE и файле логов вне контейнера, а с его удалением и вовсе пропадут. Том показывает, куда нужно сохранять изменения, которые принес в файлы, на наш хост. И куда смотреть, чтобы синхронизировать изменения на хосте со своими. К примеру если внесешь изменения в файл, контейнер их сразу увидит и скопирует к себе. Простыми словами - синхронизация
#      - ./api:/usr/src/api # в данном случае используется анонимный том, т.е. без имени. Первым параметром перед ":" указывается папка хоста, вторым - папка контейнера. В данном случае - все файлы из текущей папки будут копироваться в папку /usr/src/api в контейнере
#    command: air # без air она бы выглядела так: go run cmd/main.go -b 0.0.0.0 (также команду можно указать прямо в Dockerfile через CMD ...)
#    depends_on: # указываем, что контейнер api-markbot зависит от контейнера postgres-db-markbot. Т.е. при запуске контейнера api-markbot он будет ждать пока postgres-db-markbot будет запущен
#      - db
#      - redis
#  db:
#    image: postgres:alpine # фактически эта та же штучка, что и FROM в Dockerfile, но тк на не нужны никакие доп действия, целый Dockerfile создавать нет смысла (вареное яйцо)
#    ports:
#      - "5432:5432"
#    environment: # Возьмет из .env. Куда и что с ними делать - сам разберется
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#    volumes:
#      - postgres-db-markbot1:/var/lib/postgresql/data # тут уже используется именованный том. postgres-db-markbot - это имя тома, а /var/lib/postgresql/data - путь внутри контейнера (кто не знал, данные БД хранятся в файликах, где ж еще SQLite на максималках)
#  redis:
#    image: redis:latest
#    ports:
#      - '6379:6379'
#    volumes:
#      - redis-db-markbot1:/data
#
#volumes: # А вот тут регистрируем наш именной том. Он тоже хранится, но где - за это отвечает сам докер, например в /var/lib/docker/volumes. Именованные тома можно синхронизировать сразу между несколькими проектами и контейнерами, если хост один и тот же. Напрмер при подключении другого проекта можете указать postgres-db-markbot, и он будет видеть бд этого проекта
#  postgres-db-markbot1:
#  redis-db-markbot1:
#
version: '3.8'

services:
  # Database service - name "db" matches DB_HOST in .env
  db:
    image: postgres:14-alpine
    container_name: ${DB_HOST:-db}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db-markbot:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis service - name "redis" matches REDIS_HOST in .env
  redis:
    image: redis:7-alpine
    container_name: ${REDIS_HOST:-redis}
    ports:
      - '6379:6379'
    volumes:
      - redis-db-markbot:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Development service with hot-reloading
  api-markbot:
    build:
      context: ./api  # здесь мы говорим, где берем рецепт для нашего web контейнера. Но некоторые крутые пишут параметры context:... и dockerfile:..., если место и имя файла отличается
    container_name: markbot-api
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - GO111MODULE=on
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - api-go-mod-cache:/go/pkg/mod
    command: air -c .air.toml
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped


volumes:
  postgres-db-markbot:
    name: markbot-postgres-data
  redis-db-markbot:
    name: markbot-redis-data
  api-go-mod-cache:
    name: markbot-go-mod-cache
