version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    stop_grace_period: 0.1s
    volumes:
      - .:/usr/src/app
    command: air # без air она бы выглядела так: go run cmd/main.go -b 0.0.0.0
